# Generated by Django 5.1.3 on 2026-10-10 05:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social', '0013_cover_bounds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_membership_id', models.PositiveBigIntegerField()),
                ('second_membership_id', models.PositiveBigIntegerField()),
                ('sequence', models.PositiveBigIntegerField(default=0)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('couple', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='private_chat', to='social.couplemodel')),
                ('first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couple_chat_first', to=settings.AUTH_USER_MODEL)),
                ('second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couple_chat_second', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveBigIntegerField()),
                ('kind', models.CharField(choices=[('room.created', 'Created'), ('room.revoked', 'Revoked')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='couple_chat.room')),
            ],
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(condition=models.Q(('first_id__lt', models.F('second_id'))), name='cc_ordered_participants'),
        ),
        migrations.AddIndex(
            model_name='change',
            index=models.Index(fields=['dispatched_at', 'id'], name='cc_dispatch_idx'),
        ),
        migrations.AddConstraint(
            model_name='change',
            constraint=models.UniqueConstraint(fields=('room', 'sequence'), name='cc_unique_change_sequence'),
        ),
    ]
