# Generated by Django 6.0.3 on 2026-10-10 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_device_sessions'),
        ('couple_chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='change',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='change',
            name='kind',
            field=models.CharField(max_length=32),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('registration_id', models.PositiveIntegerField()),
                ('identity_key', models.TextField()),
                ('signed_prekey', models.JSONField()),
                ('registration_digest', models.CharField(max_length=64)),
                ('revoked_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.devicesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BundleClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.UUIDField()),
                ('bundle', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='couple_chat.room')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claimed_bundles', to='couple_chat.device')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_claims', to='couple_chat.device')),
            ],
        ),
        migrations.CreateModel(
            name='KeyPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.UUIDField()),
                ('digest', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='couple_chat.device')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='couple_chat.device')),
                ('reply_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='couple_chat.message')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='couple_chat.room')),
            ],
        ),
        migrations.CreateModel(
            name='MutationHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=24)),
                ('version', models.PositiveBigIntegerField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='couple_chat.device')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='couple_chat.message')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.UUIDField()),
                ('kind', models.CharField(max_length=24)),
                ('target_id', models.UUIDField()),
                ('version', models.PositiveBigIntegerField(default=0)),
                ('applied', models.BooleanField(default=True)),
                ('signal_type', models.PositiveSmallIntegerField()),
                ('ciphertext', models.TextField()),
                ('digest', models.CharField(max_length=64)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('change', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operation', to='couple_chat.change')),
                ('recipient_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_operations', to='couple_chat.device')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='couple_chat.room')),
                ('sender_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_operations', to='couple_chat.device')),
            ],
        ),
        migrations.CreateModel(
            name='PreKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ec', 'EC'), ('kyber', 'Kyber')], max_length=8)),
                ('key_id', models.PositiveIntegerField()),
                ('public_key', models.TextField()),
                ('signature', models.TextField(blank=True)),
                ('consumed_at', models.DateTimeField(null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prekeys', to='couple_chat.device')),
            ],
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('user',), name='cc_one_active_device'),
        ),
        migrations.AddConstraint(
            model_name='bundleclaim',
            constraint=models.UniqueConstraint(fields=('room', 'requester', 'operation_id'), name='cc_unique_bundle_claim'),
        ),
        migrations.AddConstraint(
            model_name='keypublication',
            constraint=models.UniqueConstraint(fields=('device', 'operation_id'), name='cc_unique_publication'),
        ),
        migrations.AddConstraint(
            model_name='mutationhead',
            constraint=models.UniqueConstraint(fields=('message', 'actor', 'kind'), name='cc_unique_mutation_head'),
        ),
        migrations.AddConstraint(
            model_name='operation',
            constraint=models.UniqueConstraint(fields=('room', 'actor', 'operation_id'), name='cc_unique_operation'),
        ),
        migrations.AddIndex(
            model_name='prekey',
            index=models.Index(fields=['device', 'kind', 'consumed_at'], name='cc_available_key_idx'),
        ),
        migrations.AddConstraint(
            model_name='prekey',
            constraint=models.UniqueConstraint(fields=('device', 'kind', 'key_id'), name='cc_unique_prekey'),
        ),
    ]
