# Generated by Django 6.0.3 on 2026-10-10 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couple_chat', '0002_change_metadata_alter_change_kind_device_bundleclaim_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='attachment_ids',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('intended_message_id', models.UUIDField()),
                ('ciphertext_size', models.PositiveIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('blob', models.FileField(blank=True, max_length=240, upload_to='')),
                ('uploaded_at', models.DateTimeField(null=True)),
                ('ready_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='couple_chat.device')),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='couple_chat.message')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='couple_chat.room')),
            ],
            options={
                'indexes': [models.Index(fields=['room', 'deleted_at'], name='cc_media_quota_idx'), models.Index(fields=['message', 'expires_at'], name='cc_media_orphan_idx')],
            },
        ),
    ]
