# Generated by Django 6.0.3 on 2026-10-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couple_chat', '0003_operation_attachment_ids_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileCleanup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
