# Generated by Django 6.0.3 on 2026-10-10 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couple_chat', '0004_filecleanup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Spark',
            fields=[
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='couple_chat.message')),
                ('revealed_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_sparks', to='couple_chat.device')),
                ('second_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_sparks', to='couple_chat.device')),
            ],
        ),
        migrations.CreateModel(
            name='SparkAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.UUIDField()),
                ('envelope', models.JSONField()),
                ('digest', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('spark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='couple_chat.spark')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('spark', 'actor'), name='cc_one_spark_answer')],
            },
        ),
    ]
