# Generated by Django 6.0.3 on 2026-04-11 07:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='chats/media/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chat_type', models.CharField(choices=[('single', 'Single'), ('couple', 'Couple')], default='single', max_length=10)),
                ('unread_count', models.JSONField(blank=True, default=dict)),
                ('is_typing', models.JSONField(blank=True, default=dict)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('couple', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='social.couplemodel')),
                ('singles', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='social.singleconnectionmodel')),
                ('user_one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms_as_user_one', to=settings.AUTH_USER_MODEL)),
                ('user_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms_as_user_two', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Room',
                'verbose_name_plural': 'Chat Rooms',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('AUDIO', 'Audio')], default='TEXT', max_length=20)),
                ('text', models.TextField(blank=True, null=True)),
                ('media', models.FileField(blank=True, null=True, upload_to='messages/media/')),
                ('media_url', models.URLField(blank=True, max_length=500, null=True)),
                ('sticker_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('is_delivered', models.BooleanField(db_index=True, default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('is_edited', models.BooleanField(default=False)),
                ('deleted_message', models.CharField(blank=True, max_length=100, null=True)),
                ('delete_option', models.CharField(choices=[('DELETED', 'deleted'), ('NOT_DELETED', 'Not deleted'), ('DELETE_FOR_ME', 'Delete for me'), ('DELETE_FOR_EVERYONE', 'Delete for everyone'), ('CONVERSATION_DELETED', 'Conversation deleted')], default='NOT_DELETED', max_length=20)),
                ('message_deletion_dict', models.JSONField(blank=True, null=True)),
                ('delete_for', models.JSONField(blank=True, null=True)),
                ('reactions', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom')),
                ('couple', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='social.couplemodel')),
                ('medias', models.ManyToManyField(blank=True, related_name='messages', to='chat.mediamodel')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.messagemodel')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('singles', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='social.singleconnectionmodel')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MessageDeletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_option', models.CharField(choices=[('DELETED', 'deleted'), ('NOT_DELETED', 'Not deleted'), ('DELETE_FOR_ME', 'Delete for me'), ('DELETE_FOR_EVERYONE', 'Delete for everyone'), ('CONVERSATION_DELETED', 'Conversation deleted')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='message_deletions', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletions', to='chat.messagemodel')),
            ],
        ),
        migrations.AddField(
            model_name='chatroom',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_message_for_rooms', to='chat.messagemodel'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='pinned_messages',
            field=models.ManyToManyField(blank=True, related_name='pinned_in_rooms', to='chat.messagemodel'),
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('HAHA', 'Haha'), ('WOW', 'Wow'), ('SAD', 'Sad'), ('ANGRY', 'Angry'), ('Love', 'Love')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reaction_records', to='chat.messagemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='messagemodel',
            index=models.Index(fields=['chat_room', '-timestamp'], name='chat_messag_chat_ro_ae777a_idx'),
        ),
        migrations.AddIndex(
            model_name='messagemodel',
            index=models.Index(fields=['sender', '-timestamp'], name='chat_messag_sender__86c062_idx'),
        ),
        migrations.AddIndex(
            model_name='messagemodel',
            index=models.Index(fields=['reply_to'], name='chat_messag_reply_t_5091b6_idx'),
        ),
        migrations.AddIndex(
            model_name='messagedeletion',
            index=models.Index(fields=['message', 'user'], name='chat_messag_message_f08823_idx'),
        ),
        migrations.AddConstraint(
            model_name='messagedeletion',
            constraint=models.UniqueConstraint(fields=('message', 'user', 'delete_option'), name='unique_message_user_delete_option'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['updated_at'], name='chat_chatro_updated_79f21c_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['chat_type'], name='chat_chatro_chat_ty_037291_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatroom',
            constraint=models.UniqueConstraint(fields=('user_one', 'user_two'), name='unique_chatroom_users'),
        ),
        migrations.AddIndex(
            model_name='messagereaction',
            index=models.Index(fields=['message'], name='chat_messag_message_4e17fc_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereaction',
            index=models.Index(fields=['user'], name='chat_messag_user_id_d967ff_idx'),
        ),
        migrations.AddConstraint(
            model_name='messagereaction',
            constraint=models.UniqueConstraint(fields=('message', 'user'), name='unique_message_user_reaction'),
        ),
    ]
