# Generated by Django 5.1.3 on 2024-12-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoupleConnectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_number', models.CharField(max_length=15)),
                ('receiver_number', models.CharField(max_length=15)),
                ('connection_status', models.CharField(choices=[('NOTHING', 'Nothing'), ('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('BREAK-UP', 'Break-Up')], default='NOTHING', max_length=20)),
                ('breakup_reason', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
