# Generated by Django 6.0.3 on 2026-04-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='delete_for',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='message_deletion_dict',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='reactions',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
