# Generated by Django 5.1.3 on 2024-12-13 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_coupleconnectionmodel_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupleconnectionmodel',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Couple_Connection'},
        ),
        migrations.CreateModel(
            name='CoupleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anniversary_date', models.DateField(blank=True, null=True)),
                ('shared_interests', models.JSONField(blank=True, null=True)),
                ('relationship_tagline', models.CharField(blank=True, max_length=30, null=True)),
                ('photo_album', models.JSONField(blank=True, null=True)),
                ('female_nickname_for_male', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the couple was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the couple data was last updated.')),
                ('couple_connection_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couple_connection_model', to='chat.coupleconnectionmodel')),
                ('female_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='female_partner', to=settings.AUTH_USER_MODEL)),
                ('male_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='male_partner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Couple',
                'verbose_name_plural': 'Couples',
                'ordering': ['-created_at'],
            },
        ),
    ]
