# Generated by Django 6.0.3 on 2026-10-01 14:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_messagemodel_delete_for_and_more'),
        ('social', '0011_couple_profile_sections'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='profile_action',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='profile_request_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='messagemodel',
            constraint=models.UniqueConstraint(fields=('sender', 'profile_request_id'), name='unique_profile_message_request'),
        ),
    ]
