# Generated by Django 5.1.3 on 2024-12-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_coupleconnectionmodel_options_couplemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couplemodel',
            old_name='female_nickname_for_male',
            new_name='nickname_for_female',
        ),
        migrations.AddField(
            model_name='couplemodel',
            name='nickname_for_male',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
