# Generated by Django 5.1.3 on 2024-12-14 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_rename_female_nickname_for_male_couplemodel_nickname_for_female_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoAlbumModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='couple_album/')),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couple_photo_album', to='chat.couplemodel')),
            ],
        ),
    ]
