# Generated by Django 5.1.4 on 2025-01-16 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_mediamodel_messagemodel_chat_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagemodel',
            name='chat_media',
        ),
    ]
