# Generated by Django 5.1.4 on 2025-01-16 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_remove_messagemodel_chat_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='media_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
