# Generated by Django 5.1.7 on 2025-03-20 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_singleconnectionmodel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coupleconnectionmodel',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='singleconnectionmodel',
            unique_together=set(),
        ),
    ]
