# Generated by Django 5.1.7 on 2025-04-16 14:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_alter_coupleconnectionmodel_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagemodel',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='delete_for',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='delete_option',
            field=models.CharField(choices=[('DELETED', 'deleted'), ('NOT_DELETED', 'Not deleted'), ('DELETE_FOR_ME', 'Delete for me'), ('DELETE_FOR_EVERYONE', 'Delete for everyone'), ('CONVERSATION_DELETED', 'Conversation deleted')], default='NOT_DELETED', max_length=20),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='medias',
            field=models.ManyToManyField(blank=True, related_name='message_models', to='chat.mediamodel'),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='message_deletion_dict',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='reactions',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='singles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_models', to='chat.singleconnectionmodel'),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='sticker_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='couple',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_models', to='chat.couplemodel'),
        ),
        migrations.AlterField(
            model_name='singleconnectionmodel',
            name='connection_status',
            field=models.CharField(choices=[('NOTHING', 'Nothing'), ('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('BLOCKED', 'Blocked')], default='NOTHING', max_length=20),
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('chat_type', models.CharField(choices=[('single', 'Single'), ('couple', 'Couple')], default='single', max_length=10)),
                ('unread_count', models.JSONField(default=dict)),
                ('is_typing', models.JSONField(default=dict)),
                ('settings', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='chat.couplemodel')),
                ('last_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_message_chat', to='chat.messagemodel')),
                ('messages', models.ManyToManyField(blank=True, related_name='chat_rooms', to='chat.messagemodel')),
                ('pinned_messages', models.ManyToManyField(blank=True, related_name='pinned_in_chat', to='chat.messagemodel')),
                ('singles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='chat.singleconnectionmodel')),
            ],
            options={
                'verbose_name': 'ChatRoom',
                'verbose_name_plural': 'ChatRooms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='chat_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_models', to='chat.chatroom'),
        ),
    ]
