# Generated by Django 5.1.7 on 2025-04-16 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_alter_messagemodel_options_messagemodel_delete_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='couple',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='chat.couplemodel'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='last_message',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_message_chat', to='chat.messagemodel'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='messages',
            field=models.ManyToManyField(blank=True, null=True, related_name='chat_rooms', to='chat.messagemodel'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='singles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='chat.singleconnectionmodel'),
        ),
    ]
