# Generated by Django 5.1.7 on 2025-04-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_alter_chatroom_couple_alter_chatroom_last_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='is_typing',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='settings',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='unread_count',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
