# Generated by Django 5.1.7 on 2025-05-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_alter_chatroom_is_typing_alter_chatroom_settings_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='singleconnectionmodel',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Single_Connection'},
        ),
        migrations.AddIndex(
            model_name='coupleconnectionmodel',
            index=models.Index(fields=['sender_number', 'receiver_number', 'connection_status'], name='chat_couple_sender__40b95a_idx'),
        ),
    ]
