# Generated by Django 5.1.7 on 2025-05-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_alter_singleconnectionmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='singleconnectionmodel',
            options={'ordering': ['-updated_at'], 'verbose_name': ('Single_Connection',)},
        ),
        migrations.AddIndex(
            model_name='singleconnectionmodel',
            index=models.Index(fields=['sender_number', 'receiver_number', 'connection_status'], name='chat_single_sender__f166a4_idx'),
        ),
    ]
