# Generated by Django 5.1.7 on 2025-06-27 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_alter_singleconnectionmodel_options_and_more'),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couplemodel',
            name='couple_connection_model',
        ),
        migrations.RemoveField(
            model_name='couplemodel',
            name='female_partner',
        ),
        migrations.RemoveField(
            model_name='couplemodel',
            name='male_partner',
        ),
        migrations.RemoveField(
            model_name='photoalbummodel',
            name='couple',
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='couple',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_models', to='social.couplemodel'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='couple',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='social.couplemodel'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='singles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='social.singleconnectionmodel'),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='singles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_models', to='social.singleconnectionmodel'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='chat_rooms', to='chat.messagemodel'),
        ),
        migrations.DeleteModel(
            name='CoupleConnectionModel',
        ),
        migrations.DeleteModel(
            name='PhotoAlbumModel',
        ),
        migrations.DeleteModel(
            name='CoupleModel',
        ),
        migrations.DeleteModel(
            name='SingleConnectionModel',
        ),
    ]
