# Generated by Django 5.1.7 on 2025-06-30 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_remove_couplemodel_couple_connection_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagemodel',
            name='chat_room',
        ),
        migrations.RemoveField(
            model_name='messagemodel',
            name='couple',
        ),
        migrations.RemoveField(
            model_name='messagemodel',
            name='medias',
        ),
        migrations.RemoveField(
            model_name='messagemodel',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='messagemodel',
            name='reply_to',
        ),
        migrations.RemoveField(
            model_name='messagemodel',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='messagemodel',
            name='singles',
        ),
        migrations.RemoveField(
            model_name='messagereaction',
            name='messageModel',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='MessageModel',
        ),
        migrations.DeleteModel(
            name='MessageReaction',
        ),
    ]
