# Generated by Django 5.1.7 on 2025-06-30 13:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_remove_messagemodel_chat_room_and_more'),
        ('social', '0003_couplemodel_shared_dreams'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('chat_type', models.CharField(choices=[('single', 'Single'), ('couple', 'Couple')], default='single', max_length=10)),
                ('unread_count', models.JSONField(blank=True, default=dict, null=True)),
                ('is_typing', models.JSONField(blank=True, default=dict, null=True)),
                ('settings', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('couple', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='social.couplemodel')),
                ('singles', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='social.singleconnectionmodel')),
            ],
            options={
                'verbose_name': 'ChatRoom',
                'verbose_name_plural': 'ChatRooms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('AUDIO', 'Audio')], default='TEXT', max_length=10)),
                ('text', models.TextField(blank=True, null=True)),
                ('media', models.FileField(blank=True, null=True, upload_to='messages/media/')),
                ('media_url', models.URLField(blank=True, max_length=500, null=True)),
                ('sticker_url', models.URLField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('is_delivered', models.BooleanField(default=False)),
                ('deleted_message', models.CharField(blank=True, max_length=100, null=True)),
                ('delete_option', models.CharField(choices=[('DELETED', 'deleted'), ('NOT_DELETED', 'Not deleted'), ('DELETE_FOR_ME', 'Delete for me'), ('DELETE_FOR_EVERYONE', 'Delete for everyone'), ('CONVERSATION_DELETED', 'Conversation deleted')], default='NOT_DELETED', max_length=20)),
                ('message_deletion_dict', models.JSONField(blank=True, null=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('delete_for', models.JSONField(default=dict)),
                ('reactions', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('chat_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_models', to='chat.chatroom')),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_models', to='social.couplemodel')),
                ('medias', models.ManyToManyField(blank=True, related_name='message_models', to='chat.mediamodel')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.messagemodel')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('singles', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_models', to='social.singleconnectionmodel')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='chatroom',
            name='last_message',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_message_chat', to='chat.messagemodel'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='chat_rooms', to='chat.messagemodel'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='pinned_messages',
            field=models.ManyToManyField(blank=True, related_name='pinned_in_chat', to='chat.messagemodel'),
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(blank=True, choices=[('HAHA', 'Haha'), ('WOW', 'Wow'), ('SAD', 'Sad'), ('ANGRY', 'Angry'), ('Love', 'Love')], max_length=20, null=True)),
                ('messageModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.messagemodel')),
            ],
        ),
    ]
