# Generated by Django 5.1.7 on 2025-09-21 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_chatroom_messagemodel_chatroom_last_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='singles',
        ),
        migrations.RemoveField(
            model_name='messagemodel',
            name='singles',
        ),
    ]
