# Generated by Django 5.1.7 on 2025-09-21 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_remove_chatroom_singles_remove_messagemodel_singles'),
        ('social', '0006_singleconnectionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='singles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='social.singleconnectionmodel'),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='singles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_models', to='social.singleconnectionmodel'),
        ),
    ]
