# Generated by Django 5.1.7 on 2025-11-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0021_chatroom_singles_messagemodel_singles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='delete_for',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
