# Generated by Django 5.1.7 on 2025-11-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_alter_messagemodel_delete_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='reactions',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
