# Generated by Django 5.1.7 on 2025-11-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0023_alter_messagemodel_reactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='delete_for',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='reactions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
