# Generated by Django 5.1.7 on 2025-12-23 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0024_alter_messagemodel_delete_for_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageDeletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('delete_option', models.CharField(blank=True, choices=[('DELETED', 'deleted'), ('NOT_DELETED', 'Not deleted'), ('DELETE_FOR_ME', 'Delete for me'), ('DELETE_FOR_EVERYONE', 'Delete for everyone'), ('CONVERSATION_DELETED', 'Conversation deleted')], max_length=20, null=True)),
                ('messageModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletions', to='chat.messagemodel')),
            ],
        ),
    ]
