# Generated by Django 5.1.7 on 2025-12-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0025_messagedeletion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='messagedeletion',
            unique_together={('messageModel', 'user_id', 'delete_option')},
        ),
        migrations.AddIndex(
            model_name='messagedeletion',
            index=models.Index(fields=['messageModel', 'user_id', 'delete_option'], name='chat_messag_message_16dc52_idx'),
        ),
    ]
