# Generated by Django 5.1.7 on 2025-12-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0026_alter_messagedeletion_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
