# Generated by Django 6.0.1 on 2026-01-20 15:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0027_messagemodel_is_sent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='chat_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
