# Generated by Django 6.0.1 on 2026-01-20 15:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0028_chatroom_users'),
        ('social', '0006_singleconnectionmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='users',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='user_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms_as_user_one', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='user_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms_as_user_two', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='is_typing',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_message_chat', to='chat.messagemodel'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='unread_count',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddConstraint(
            model_name='chatroom',
            constraint=models.UniqueConstraint(fields=('user_one', 'user_two'), name='unique_chatroom_users'),
        ),
    ]
