# Generated by Django 6.0.1 on 2026-01-31 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0029_remove_chatroom_users_chatroom_user_one_and_more'),
        ('social', '0006_singleconnectionmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='couple',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_models', to='social.couplemodel'),
        ),
    ]
