# Generated by Django 5.1.3 on 2024-11-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
