# Generated by Django 5.1.3 on 2024-11-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_otpmodel_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpmodel',
            name='otp_status',
            field=models.CharField(choices=[('NOTHING', 'nothing'), ('NEW', 'new'), ('EXPIRED', 'expired')], default='NOTHING', max_length=15),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
