# Generated by Django 5.1.3 on 2024-12-13 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_usermodel_email_alter_usermodel_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usermodel',
            managers=[
            ],
        ),
    ]
