# Generated by Django 5.1.4 on 2025-03-11 23:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_usermodel_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpmodel',
            name='last_request_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='otpmodel',
            name='otp_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
