# Generated by Django 5.1.7 on 2025-05-14 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_usermodel_bio_userinterestmodel_userphotoalbummodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferencemodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to=settings.AUTH_USER_MODEL),
        ),
    ]
