# Generated by Django 5.1.7 on 2025-05-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0009_alter_userpreferencemodel_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'ordering': ['-created_date'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='usermodel',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='usermodel',
            index=models.Index(fields=['phone_number', 'full_name', 'gender', 'zodiac_sign'], name='authenticat_phone_n_0288d3_idx'),
        ),
    ]
