# Generated by Django 5.1.7 on 2025-05-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0010_alter_usermodel_options_usermodel_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinterestmodel',
            options={'ordering': ['name'], 'verbose_name': 'User Interest', 'verbose_name_plural': 'User Interests'},
        ),
        migrations.AlterModelOptions(
            name='userpreferencemodel',
            options={'ordering': ['user'], 'verbose_name': 'User Preference', 'verbose_name_plural': 'User Preferences'},
        ),
        migrations.RemoveIndex(
            model_name='usermodel',
            name='authenticat_phone_n_0288d3_idx',
        ),
        migrations.AddField(
            model_name='userpreferencemodel',
            name='zodiac_sign',
            field=models.CharField(blank=True, choices=[('ARIES', 'Aries'), ('TAURUS', 'Taurus'), ('GEMINI', 'Gemini'), ('CANCER', 'Cancer'), ('LEO', 'Leo'), ('VIRGO', 'Virgo'), ('LIBRA', 'Libra'), ('SCORPIO', 'Scorpio'), ('SAGITTARIUS', 'Sagittarius'), ('CAPRICORN', 'Capricorn'), ('AQUARIUS', 'Aquarius'), ('PISCES', 'Pisces')], max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='userinterestmodel',
            index=models.Index(fields=['user', 'name'], name='authenticat_user_id_ebbc6d_idx'),
        ),
        migrations.AddIndex(
            model_name='usermodel',
            index=models.Index(fields=['phone_number', 'full_name', 'gender', 'zodiac_sign', 'city', 'country'], name='authenticat_phone_n_058554_idx'),
        ),
        migrations.AddIndex(
            model_name='userpreferencemodel',
            index=models.Index(fields=['user'], name='authenticat_user_id_9f0256_idx'),
        ),
    ]
