# Generated by Django 5.1.7 on 2025-06-27 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_userinterestmodel_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPreferenceModel',
        ),
    ]
