# Generated by Django 5.1.7 on 2025-08-11 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_interestcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinterestmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_interests', to='authentication.interestcategory'),
        ),
    ]
