# Generated by Django 5.1.7 on 2025-08-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_remove_userinterestmodel_category_interestmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinterestmodel',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
