# Generated by Django 5.1.7 on 2025-08-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_userinterestmodel_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userphotoalbummodel',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
