# Generated by Django 6.0.1 on 2026-03-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_userphotoalbummodel_removed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userphotoalbummodel',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
