# Generated by Django 6.0.1 on 2026-03-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_alter_userphotoalbummodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
