# Generated by Django 6.0.3 on 2026-06-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_alter_usermodel_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_engaged',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
