# Generated by Django 6.0.3 on 2026-09-28 14:26

import django.utils.timezone
import uuid
from django.db import migrations, models


def preflight_and_invalidate(apps, schema_editor):
    User = apps.get_model("authentication", "UserModel")
    duplicates = User.objects.exclude(username__isnull=True).exclude(username="").values("username").annotate(n=models.Count("id")).filter(n__gt=1).count()
    if duplicates:
        raise RuntimeError(f"Authentication migration blocked: {duplicates} duplicate username groups. Review and resolve with affected users; no accounts were renamed.")
    # Existing short-lived proofs must not survive the switch from plaintext to HMAC.
    apps.get_model("authentication", "OtpModel").objects.update(otp_code="", otp_status="EXPIRED")



class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0020_usermodel_is_engaged'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpRequestBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, unique=True)),
                ('window_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='otpmodel',
            name='challenge_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='otpmodel',
            name='delivery_state',
            field=models.CharField(default='failed', max_length=12),
        ),
        migrations.AddField(
            model_name='otpmodel',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otpmodel',
            name='failed_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='otpmodel',
            name='request_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otpmodel',
            name='resend_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='profile_photo_skipped',
            field=models.BooleanField(default=False, db_default=False),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='otp_code',
            field=models.CharField(max_length=128),
        ),
        migrations.RunPython(preflight_and_invalidate, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='usermodel',
            constraint=models.UniqueConstraint(condition=models.Q(('username__isnull', False), models.Q(('username', ''), _negated=True)), fields=('username',), name='auth_unique_nonempty_username'),
        ),
    ]
