"""
Django settings for srisu project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DJANGO_DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = [host.strip() for host in config("DJANGO_ALLOWED_HOSTS", default="localhost,127.0.0.1").split(",") if host.strip()]


# Application definition

INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "psycopg2",
    "authentication",
    "rest_framework_simplejwt",
    "rest_framework.authtoken",
    "chat",
    "rest_framework_simplejwt.token_blacklist",
    "channels",
    "social"
]

MIDDLEWARE = [
    "srisu.api.middleware.RequestContextMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "srisu.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "srisu.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("POSTGRES_DB"),
        "USER": config("POSTGRES_USER"),
        "PASSWORD": config("POSTGRES_PASSWORD"),
        "HOST": config("POSTGRES_HOST"),
        "PORT": "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
MEDIA_ROOT = "media/"
MEDIA_URL = "/media/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

ASGI_APPLICATION = "srisu.asgi.application"

CHANNEL_LAYERS = {
    "default":{
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts":[(config("REDIS_HOST", default="redis"),config("REDIS_PORT", default=6379))],
        },
    },
}

AUTH_USER_MODEL = "authentication.UserModel"

# Separate namespace from Channels. Only short-lived ordered IDs are cached.
CACHES = {
    "default": {"BACKEND": "django.core.cache.backends.locmem.LocMemCache"},
    "couple_feed": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": config("COUPLE_FEED_REDIS_URL", default="redis://%s:%s/1" % (
            config("REDIS_HOST", default="redis"), config("REDIS_PORT", default=6379))),
        "KEY_PREFIX": "srisu-couple-feed",
        "OPTIONS": {"socket_connect_timeout": 1, "socket_timeout": 1},
    },
}
COUPLE_FEED_ENABLED = config("COUPLE_FEED_ENABLED", default=True, cast=bool)
COUPLE_FEED_SESSION_TTL = 15 * 60
COUPLE_FEED_CANDIDATE_LIMIT = 500
COUPLE_FEED_EXPLORATION_INTERVAL = 10
COUPLE_FEED_RANKING_VERSION = "couple-v1"
COUPLE_FEED_WEIGHTS = {"interests": 40, "location": 25, "fave": 20, "freshness": 15}

REST_FRAMEWORK = {
    "DEFAULT_THROTTLE_RATES": {"chat_reads": "120/min"},
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "EXCEPTION_HANDLER": "utils.exception_handlers.custom_exception_handler",
    "DEFAULT_PARSER_CLASSES" :[
        'drf_nested_forms.parsers.NestedMultiPartParser',
        'drf_nested_forms.parsers.NestedJSONParser',
        'rest_framework.parsers.FormParser',
    ]
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=365 * 10),  # For 10 years.
    "REFRESH_TOKEN_LIFETIME": timedelta(days=365 * 10),
    "AUTH_HEADER_TYPES": ("Bearer",),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}


TWILIO_ACCOUNT_SID = config("TWILIO_ACCOUNT_SID")
TWILIO_AUTH_TOKEN = config("TWILIO_AUTH_TOKEN")
TWILIO_PHONE_NUMBER = config("TWILIO_PHONE_NUMBER")


# Native clients use bearer headers; browser origins are explicitly allowlisted.
WEBSOCKET_ALLOWED_ORIGINS = [origin.strip() for origin in config("WEBSOCKET_ALLOWED_ORIGINS", default="").split(",") if origin.strip()]
WS_MAX_FRAME_BYTES = 64 * 1024
WS_COMMAND_BURST = 30
WS_COMMANDS_PER_SECOND = 10
WS_MAX_SUBSCRIPTIONS = 20

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {"core": {"()": "srisu.api.logging.CoreJsonFormatter"}},
    "handlers": {"core": {"class": "logging.StreamHandler", "formatter": "core"}},
    "loggers": {"srisu": {"handlers": ["core"], "level": "INFO", "propagate": False}},
}
