"""
Django settings for srisu project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DJANGO_DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = [host.strip() for host in config("DJANGO_ALLOWED_HOSTS", default="localhost,127.0.0.1").split(",") if host.strip()]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "psycopg2",
    "authentication",
    "rest_framework_simplejwt",
    "rest_framework.authtoken",
    "chat",
    "rest_framework_simplejwt.token_blacklist",
    "social"
]

MIDDLEWARE = [
    "srisu.api.middleware.RequestContextMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "srisu.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "srisu.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("POSTGRES_DB"),
        "USER": config("POSTGRES_USER"),
        "PASSWORD": config("POSTGRES_PASSWORD"),
        "HOST": config("POSTGRES_HOST"),
        "PORT": config("POSTGRES_PORT", default=5432, cast=int),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
MEDIA_ROOT = "media/"
MEDIA_URL = "/media/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

ASGI_APPLICATION = "srisu.asgi.application"

AUTH_USER_MODEL = "authentication.UserModel"

# Dedicated namespace for short-lived couple-feed ordering IDs.
CACHES = {
    "default": {"BACKEND": "django.core.cache.backends.locmem.LocMemCache"},
    "couple_feed": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": config("COUPLE_FEED_REDIS_URL", default="redis://%s:%s/1" % (
            config("REDIS_HOST", default="redis"), config("REDIS_PORT", default=6379))),
        "KEY_PREFIX": "srisu-couple-feed",
        "OPTIONS": {"socket_connect_timeout": 1, "socket_timeout": 1},
    },
}
COUPLE_FEED_ENABLED = config("COUPLE_FEED_ENABLED", default=True, cast=bool)
COUPLE_FEED_SESSION_TTL = 15 * 60
COUPLE_FEED_CANDIDATE_LIMIT = 500
COUPLE_FEED_EXPLORATION_INTERVAL = 10
COUPLE_FEED_RANKING_VERSION = "couple-v1"
COUPLE_FEED_WEIGHTS = {"interests": 40, "location": 25, "fave": 20, "freshness": 15}

REST_FRAMEWORK = {
    "DEFAULT_THROTTLE_RATES": {
        "partner_discovery": "20/min",
        "chat_matrix_session": "10/min",
    },
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "authentication.sessions.SessionJWTAuthentication",
    ],
    "EXCEPTION_HANDLER": "utils.exception_handlers.custom_exception_handler",
    "DEFAULT_PARSER_CLASSES" :[
        'drf_nested_forms.parsers.NestedMultiPartParser',
        'drf_nested_forms.parsers.NestedJSONParser',
        'rest_framework.parsers.FormParser',
    ]
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=365 * 10),  # For 10 years.
    "REFRESH_TOKEN_LIFETIME": timedelta(days=365 * 10),
    "AUTH_HEADER_TYPES": ("Bearer",),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}


TWILIO_ACCOUNT_SID = config("TWILIO_ACCOUNT_SID")
TWILIO_AUTH_TOKEN = config("TWILIO_AUTH_TOKEN")
TWILIO_PHONE_NUMBER = config("TWILIO_PHONE_NUMBER")

# Explicit development delivery switch. Normal deployments still use Twilio.
OTP_MOCK_DELIVERY = config("OTP_MOCK_DELIVERY", default=False, cast=bool)
# Empty outside development Compose; ignored entirely when real delivery is enabled.
OTP_MOCK_CODE = config("OTP_MOCK_CODE", default="")


# Private Matrix remains fail-closed until a deployment supplies a reviewed
# service adapter and credentials. Django stays authoritative for account and
# current-couple authorization; Matrix carries encrypted room traffic.
MATRIX_ENABLED = config("MATRIX_ENABLED", default=False, cast=bool)
MATRIX_SERVICE_CLASS = config(
    "MATRIX_SERVICE_CLASS",
    default="chat.services.matrix_provisioning.DisabledMatrixService",
)
MATRIX_HOMESERVER_URL = config("MATRIX_HOMESERVER_URL", default="")
MATRIX_INTERNAL_HOMESERVER_URL = config("MATRIX_INTERNAL_HOMESERVER_URL", default="")
MATRIX_SERVER_NAME = config("MATRIX_SERVER_NAME", default="")
MATRIX_PROTOCOL_ID = config("MATRIX_PROTOCOL_ID", default="matrix-e2ee-v1")
MATRIX_SESSION_TTL_SECONDS = config("MATRIX_SESSION_TTL_SECONDS", default=120, cast=int)
MATRIX_ACCESS_TOKEN_LIFETIME_SECONDS = config(
    "MATRIX_ACCESS_TOKEN_LIFETIME_SECONDS",
    default=5 * 60,
    cast=int,
)
MATRIX_PROVISIONING_LOCALPART = config(
    "MATRIX_PROVISIONING_LOCALPART",
    default="srisu_provisioner",
)
MATRIX_ROOM_VERSION = config("MATRIX_ROOM_VERSION", default="11")
MATRIX_JWT_SECRET = config("MATRIX_JWT_SECRET", default="")
MATRIX_JWT_ALGORITHM = config("MATRIX_JWT_ALGORITHM", default="HS256")
MATRIX_JWT_ISSUER = config("MATRIX_JWT_ISSUER", default="srisu-django")
MATRIX_JWT_AUDIENCE = config("MATRIX_JWT_AUDIENCE", default="srisu-matrix")
MATRIX_HTTP_TIMEOUT_SECONDS = config("MATRIX_HTTP_TIMEOUT_SECONDS", default=5, cast=float)
MATRIX_PROVISION_LOCK_SECONDS = config("MATRIX_PROVISION_LOCK_SECONDS", default=60, cast=int)
MATRIX_RETRY_BASE_SECONDS = config("MATRIX_RETRY_BASE_SECONDS", default=5, cast=int)
MATRIX_RETRY_MAX_SECONDS = config("MATRIX_RETRY_MAX_SECONDS", default=300, cast=int)
MATRIX_REMOTE_VERIFY_INTERVAL_SECONDS = config(
    "MATRIX_REMOTE_VERIFY_INTERVAL_SECONDS",
    default=300,
    cast=int,
)
MATRIX_CUTOVER_ATTESTATION_TTL_SECONDS = config(
    "MATRIX_CUTOVER_ATTESTATION_TTL_SECONDS",
    default=300,
    cast=int,
)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {"core": {"()": "srisu.api.logging.CoreJsonFormatter"}},
    "handlers": {"core": {"class": "logging.StreamHandler", "formatter": "core"}},
    "loggers": {"srisu": {"handlers": ["core"], "level": "INFO", "propagate": False}},
}

# Temporary compatibility during auth-1 rollout; disable after the announced cutoff.
AUTH_ACCEPT_LEGACY_TOKENS = config("AUTH_ACCEPT_LEGACY_TOKENS", default=True, cast=bool)

OTP_GLOBAL_HOURLY_LIMIT = config("OTP_GLOBAL_HOURLY_LIMIT", default=100, cast=int)
OTP_IP_HOURLY_LIMIT = config("OTP_IP_HOURLY_LIMIT", default=10, cast=int)
