# Generated by Django 5.1.7 on 2025-06-27 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoupleConnectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_number', models.CharField(max_length=15)),
                ('receiver_number', models.CharField(max_length=15)),
                ('connection_status', models.CharField(choices=[('NOTHING', 'Nothing'), ('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('BREAK-UP', 'Break-Up')], default='NOTHING', max_length=20)),
                ('breakup_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Couple_Connection',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['sender_number', 'receiver_number', 'connection_status'], name='social_coup_sender__086e18_idx')],
            },
        ),
        migrations.CreateModel(
            name='CoupleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anniversary_date', models.DateField(blank=True, null=True)),
                ('shared_interests', models.JSONField(blank=True, null=True)),
                ('relationship_tagline', models.CharField(blank=True, max_length=30, null=True)),
                ('photo_album', models.JSONField(blank=True, null=True)),
                ('nickname_for_male', models.CharField(blank=True, max_length=30, null=True)),
                ('nickname_for_female', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the couple was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the couple data was last updated.')),
                ('couple_connection_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couple_connection_model', to='social.coupleconnectionmodel')),
                ('female_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='female_partner', to=settings.AUTH_USER_MODEL)),
                ('male_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='male_partner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Couple',
                'verbose_name_plural': 'Couples',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhotoAlbumModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='couple_album/')),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couple_photo_album', to='social.couplemodel')),
            ],
        ),
        migrations.CreateModel(
            name='SingleConnectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_number', models.CharField(max_length=15)),
                ('receiver_number', models.CharField(max_length=15)),
                ('connection_status', models.CharField(choices=[('NOTHING', 'Nothing'), ('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('BLOCKED', 'Blocked')], default='NOTHING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['sender_number', 'receiver_number', 'connection_status'], name='social_sing_sender__c9e151_idx')],
            },
        ),
    ]
