# Generated by Django 6.0.3 on 2026-04-11 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoupleConnectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_number', models.CharField(max_length=15)),
                ('receiver_number', models.CharField(max_length=15)),
                ('connection_status', models.CharField(choices=[('NOTHING', 'Nothing'), ('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('BREAK-UP', 'Break-Up')], default='NOTHING', max_length=20)),
                ('breakup_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Couple_Connection',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['sender_number', 'receiver_number', 'connection_status'], name='social_coup_sender__086e18_idx')],
            },
        ),
        migrations.CreateModel(
            name='CoupleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anniversary_date', models.DateField(blank=True, null=True)),
                ('shared_dreams', models.JSONField(blank=True, null=True)),
                ('shared_interests', models.JSONField(blank=True, null=True)),
                ('relationship_tagline', models.CharField(blank=True, max_length=30, null=True)),
                ('photo_album', models.JSONField(blank=True, null=True)),
                ('nickname_for_male', models.CharField(blank=True, max_length=30, null=True)),
                ('nickname_for_female', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the couple was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the couple data was last updated.')),
                ('couple_connection_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couple_connection_model', to='social.coupleconnectionmodel')),
                ('female_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='female_partner', to=settings.AUTH_USER_MODEL)),
                ('male_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='male_partner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Couple',
                'verbose_name_plural': 'Couples',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhotoAlbumModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='couple_album/')),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couple_photo_album', to='social.couplemodel')),
            ],
        ),
        migrations.CreateModel(
            name='SingleConnectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_number', models.CharField(max_length=15)),
                ('receiver_number', models.CharField(max_length=15)),
                ('connection_status', models.CharField(choices=[('NOTHING', 'Nothing'), ('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('BLOCKED', 'Blocked')], default='NOTHING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['sender_number', 'receiver_number', 'connection_status'], name='social_sing_sender__c9e151_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserPreferenceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_age', models.IntegerField(blank=True, default=18, null=True)),
                ('max_age', models.IntegerField(blank=True, default=35, null=True)),
                ('zodiac_sign', models.CharField(blank=True, choices=[('ARIES', 'Aries'), ('TAURUS', 'Taurus'), ('GEMINI', 'Gemini'), ('CANCER', 'Cancer'), ('LEO', 'Leo'), ('VIRGO', 'Virgo'), ('LIBRA', 'Libra'), ('SCORPIO', 'Scorpio'), ('SAGITTARIUS', 'Sagittarius'), ('CAPRICORN', 'Capricorn'), ('AQUARIUS', 'Aquarius'), ('PISCES', 'Pisces')], max_length=20, null=True)),
                ('radius_km', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
                'ordering': ['user'],
                'indexes': [models.Index(fields=['user'], name='social_user_user_id_f91f03_idx')],
            },
        ),
    ]
