# Generated by Django 5.1.7 on 2025-06-27 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferenceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_age', models.IntegerField(blank=True, default=18, null=True)),
                ('max_age', models.IntegerField(blank=True, default=35, null=True)),
                ('zodiac_sign', models.CharField(blank=True, choices=[('ARIES', 'Aries'), ('TAURUS', 'Taurus'), ('GEMINI', 'Gemini'), ('CANCER', 'Cancer'), ('LEO', 'Leo'), ('VIRGO', 'Virgo'), ('LIBRA', 'Libra'), ('SCORPIO', 'Scorpio'), ('SAGITTARIUS', 'Sagittarius'), ('CAPRICORN', 'Capricorn'), ('AQUARIUS', 'Aquarius'), ('PISCES', 'Pisces')], max_length=20, null=True)),
                ('radius_km', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
                'ordering': ['user'],
                'indexes': [models.Index(fields=['user'], name='social_user_user_id_f91f03_idx')],
            },
        ),
    ]
