# Generated by Django 6.0.3 on 2026-06-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_remove_couplemodel_photo_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='couplemodel',
            name='photo_album',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
