# Generated by Django 5.1.7 on 2025-06-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_userpreferencemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='couplemodel',
            name='shared_dreams',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
