# Generated by Django 6.0.3 on 2026-06-23 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_couplemodel_photo_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couplemodel',
            name='photo_album',
        ),
    ]
