# Generated by Django 6.0.3 on 2026-06-23 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_remove_couplemodel_photo_album'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couplemodel',
            name='couple_connection_model',
        ),
        migrations.AddField(
            model_name='couplemodel',
            name='couple_connection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='couple', to='social.coupleconnectionmodel'),
        ),
        migrations.AddField(
            model_name='couplemodel',
            name='couple_profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='couples/profile_photos/'),
        ),
        migrations.AlterField(
            model_name='couplemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='couplemodel',
            name='female_partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couples_as_female', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='couplemodel',
            name='male_partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couples_as_male', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='couplemodel',
            name='relationship_tagline',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='couplemodel',
            name='shared_dreams',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='couplemodel',
            name='shared_interests',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='couplemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
