# Generated by Django 5.1.7 on 2025-09-21 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_remove_chatroom_singles_remove_messagemodel_singles'),
        ('social', '0004_singleconnectionmodel_receiver'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SingleConnectionModel',
        ),
    ]
