# Generated by Django 5.1.7 on 2025-09-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_delete_singleconnectionmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleConnectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_number', models.CharField(max_length=15)),
                ('receiver_number', models.CharField(max_length=15)),
                ('connection_status', models.CharField(choices=[('NOTHING', 'Nothing'), ('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('BLOCKED', 'Blocked')], default='NOTHING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['sender_number', 'receiver_number', 'connection_status'], name='social_sing_sender__c9e151_idx')],
            },
        ),
    ]
