# Generated by Django 6.0.3 on 2026-06-24 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_remove_couplemodel_couple_connection_model_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoupleMomentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('caption', models.TextField(max_length=1000)),
                ('moment_date', models.DateField()),
                ('mood', models.CharField(blank=True, choices=[('happy', 'Happy'), ('romantic', 'Romantic'), ('funny', 'Funny'), ('emotional', 'Emotional'), ('adventure', 'Adventure'), ('grateful', 'Grateful'), ('special', 'Special')], max_length=30, null=True)),
                ('location_name', models.CharField(blank=True, max_length=120, null=True)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('friends', 'Friends')], default='private', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('partner_memory', models.TextField(blank=True, help_text="Partner's perspective on this moment.", max_length=1000, null=True)),
                ('is_time_capsule', models.BooleanField(default=False)),
                ('unlock_date', models.DateField(blank=True, help_text='If time capsule, moment unlocks on this date.', null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moments', to='social.couplemodel')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_couple_moments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Couple Moment',
                'verbose_name_plural': 'Couple Moments',
                'ordering': ['-moment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoupleMomentPhotoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='couples/moments/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('moment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='social.couplemomentmodel')),
            ],
            options={
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
