# Generated by Django 6.0.3 on 2026-10-01 14:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_couplefavemodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='couplemodel',
            name='cover_focal_y',
            field=models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='couplemodel',
            name='cover_source_moment_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='couple_profile_covers', to='social.couplemomentphotomodel'),
        ),
        migrations.AddField(
            model_name='couplemodel',
            name='privacy_proposal',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='couplemodel',
            name='privacy_proposal_version',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='couplemodel',
            name='revision',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='couplemodel',
            name='section_revisions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='CoupleSongModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('artist', models.CharField(blank=True, max_length=120)),
                ('band', models.CharField(blank=True, max_length=120)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('couple', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='song', to='social.couplemodel')),
                ('picked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picked_couple_songs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CouplePlanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField()),
                ('title', models.CharField(max_length=120)),
                ('starts_at', models.DateTimeField()),
                ('response', models.CharField(choices=[('pending', 'Pending'), ('yes', 'Yes'), ('no', 'No'), ('another_time', 'Another time')], default='pending', max_length=16)),
                ('response_note', models.CharField(blank=True, max_length=240)),
                ('completed', models.BooleanField(default=False)),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('audience_membership_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='social.couplemodel')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couple_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['starts_at', 'id'],
                'indexes': [models.Index(fields=['couple', 'starts_at', 'id'], name='couple_plan_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('couple', 'created_by', 'request_id'), name='unique_couple_plan_request')],
            },
        ),
        migrations.CreateModel(
            name='CouplePrivacyConsentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_version', models.PositiveBigIntegerField()),
                ('approved_at', models.DateTimeField(auto_now=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_consents', to='social.couplemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couple_privacy_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('couple', 'user'), name='unique_couple_privacy_consent')],
            },
        ),
        migrations.CreateModel(
            name='CoupleProfileChangeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=32)),
                ('action', models.CharField(default='updated', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couple_profile_changes', to=settings.AUTH_USER_MODEL)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_changes', to='social.couplemodel')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['couple', '-created_at'], name='couple_profile_history_idx')],
            },
        ),
        migrations.CreateModel(
            name='CoupleStoryAnswerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(choices=[('how_met', 'Where did you two meet?'), ('first_move', 'Who made the first move?'), ('first_impression', 'First impression, in three words')], max_length=32)),
                ('answer', models.CharField(max_length=240)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couple_story_answers', to=settings.AUTH_USER_MODEL)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_answers', to='social.couplemodel')),
            ],
            options={
                'ordering': ['prompt', 'author_id'],
                'indexes': [models.Index(fields=['couple', 'prompt'], name='couple_story_prompt_idx')],
                'constraints': [models.UniqueConstraint(fields=('couple', 'author', 'prompt'), name='unique_couple_story_answer')],
            },
        ),
    ]
