# Generated by Django 6.0.3 on 2026-10-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_couple_profile_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couplemodel',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='couples/profile_private/'),
        ),
    ]
