# Generated by Django 6.0.3 on 2026-10-01 15:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_guarded_legacy_cover_uploads'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='couplemodel',
            constraint=models.CheckConstraint(condition=models.Q(('cover_focal_y__gte', 0), ('cover_focal_y__lte', 1)), name='couple_cover_focal_bounds'),
        ),
    ]
